language: java
jdk:
  - openjdk7

before_script:
  - sh get-idea-ic.sh
  - sed -i -- "s/{{PLUGIN_VERSION}}/$TRAVIS_TAG/g" META-INF/plugin.xml

script:
  - ant -v all
  - mv TestFairyAndroidStudioPlugin.zip testfairy-intellij-$TRAVIS_TAG-bin.zip

deploy:
  provider: releases
  api_key:
    secure: joB004XJ4qkie8F/TddmgpkTmteXYDHS5/NShbAAJfenSyvwmZLo4s7Rjlvx4rVNCxZzUcZPyx/t/d0ibUpQG+iFXfsR2/tbuMlk3zBGht739dXjDk/cJjXIxZTpd5/17BOB9yB6k2w7lofHyCyEVf9qvKgWpMBgEA2JMDptpsTbsbJIYPD1mDO+Nz1f+kIcOEUaTx/EizlH5L1Iowv8w5taa8In+aYFHkK43zEhGvszLRTTZ0KxKTNOZCLgss7LbJFX0rD8ILIBzpRg32BboHZc3C1Co8fNJf0Stt9NV77lr8H02EuXpXNnk7AlbCeiohkaRx8LYuOpPyDvQV9ReoS0bDzM30WcvQH8ggnupf9agQsg06jN5ggW4IUYZyvn2C3lP02KevNHh9pQzn+z+0RMXKkpMLVCgT97C5ruV3KW0OrOW22xTo/bO7QNdKcmVV8nL0Cd6ppJcZe/rqJCWnGTePGRALTQXSjnbH3/odlKzgAUcbuHpGCiHzYpW1KdhSUXXHRFKjwOMybx/NXOxUoZuMu8rsyvn5eviNit85U4T8l7VasOO5FO5+8qdP8KkVLu3B1J4TiAXzLhqrW2c4dVdf7UUYnGkiQ5g/njrymW5RyxTMbvy/mbZeUaPEyhe0+O+sTJs2Kq5cOZcwiiSNPQeI62MiZ4c3T+rWT9a24=
  file: testfairy-intellij-$TRAVIS_TAG-bin.zip
  skip_cleanup: true
  on:
    repo: testfairy/testfairy-android-studio-plugin
    all_branches: true

